### ISSUE TITLE
Installation link broken

### ISSUE THREAD

**Issue by adam5zki** [iFrostizz/OctoPrint-CalibrationCompanion#1]
The installation via the Plugin manager fails due to a HTTP404 error. The link seems to be wrong as it does report a 404 error. The link in the description's Installation section "https://github.com/iFrostizz/OctoPrint-CalibrationCompanion/archive/master.zip" throws the same 404 error.

**Comment by dualznz** [comment]
i can confirm this error as well

**Comment by jasonmacdonald** [comment]
Someone beat me to it. It's broken! :)

**Comment by Gruvyminion** [comment]
Same:

> Installing plugin "Calibration Companion" from https://github.com/iFrostizz/OctoPrint-CalibrationCompanion/archive/master.zip...
Error!
Could not fetch plugin from server, got 404 Client Error: Not Found for url: https://codeload.github.com/iFrostizz/OctoPrint-CalibrationCompanion/zip/master

**Comment by CaptClaude** [comment]
That fixed it for me! Thanks.
