### ISSUE TITLE
More than 3 nozzle sizes

### ISSUE THREAD

**Issue by Epiphero** [iFrostizz/OctoPrint-CalibrationCompanion#14]
The nozzle size selector only has 3 options, but there are more options in the wild.  E.g. MakerGear M2 uses 0.35mm.  This should be a numerical input field, not a selection.

**Comment by iFrostizz** [comment]
Hello,
Making a numerical input field for the nozzle size would be the same as developping a slicer on Octoprint.
I am slicing and storing all the data (mostly relative coordinates) manually.
But I could add the 0.35mm for sure!
