### ISSUE TITLE
Credit your sources

### ISSUE THREAD

**Issue by in50mn14c** [iFrostizz/OctoPrint-CalibrationCompanion#2]
Kudos for starting the project as a octoprint plugin - but if you're gonna rip off TeachingTech's work you should at least credit him.

[https://teachingtechyt.github.io/calibration.html](https://teachingtechyt.github.io/calibration.html)

**Comment by iFrostizz** [comment]
Dang! I totally forgot!
Now it's added, thank you very much for mentionning this.

Enjoy!
