### ISSUE TITLE
plugin hangs after clicking 'print nnnnn'

### ISSUE THREAD

**Issue by L4RGER** [iFrostizz/OctoPrint-CalibrationCompanion#24]
after setting up one of the tests and clicking the 'print xxxxxx' button at the bottom the file is generated and then can be printed but the plug button remains as 'generating.....' and requires a restart to generate the calibration print again.

**Comment by iFrostizz** [comment]
It looks like it's working on my side, is that on a specific file, or all ?
Do you have such a message after generating the .gcode ? 
![image](https://user-images.githubusercontent.com/51274081/124214187-21445800-daf2-11eb-8b2d-08b18d50905a.png)
Do you have any error in the logs ?

**Comment by L4RGER** [comment]
Hey! 
yep it creates the file fine. I just did the first layer one again through chrome browser on my phone and it seems fine. 
I was using Firefox on my MacBook earlier, maybe it’s a Firefox issue rather than a plug in issue. 
sorry about opening this unnecessarily

**Comment by L4RGER** [comment]
Also thanks for creating this.
