### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by gummibear1986** [iFrostizz/OctoPrint-CalibrationCompanion#3]
Hi

Tried to install via URL and via Plugin Manager but getting a 404 error each time:

Error!
Could not fetch plugin from server, got 404 Client Error: Not Found for url: https://codeload.github.com/iFrostizz/OctoPrint-CalibrationCompanion/zip/master

**Comment by iFrostizz** [comment]
If someone finds this issue, please check this one: https://github.com/iFrostizz/OctoPrint-CalibrationCompanion/issues/1
