### ISSUE TITLE
CalibrationCompanion breaks Spoolmanager

### ISSUE THREAD

**Issue by GylRon1** [iFrostizz/OctoPrint-CalibrationCompanion#7]
After installing CalibrationCompanion it is impossible to add new spools in Spoolmanager. If it is disabled and Octoprint is restarted, adding spools is possible again.  I have Themeify installed. Attached an empty spool adding screen grab (the error) and a correct working screen grab.
![Add Spool empty screen](https://user-images.githubusercontent.com/84151858/118176357-9ae49180-b431-11eb-9896-04a70ca61964.png)
![Add Spool working screen](https://user-images.githubusercontent.com/84151858/118176387-a33ccc80-b431-11eb-9498-d5c4f2687d58.png)

**Comment by iFrostizz** [comment]
Do you have any error in the devtools (F12) when calibration companion is enabled ? Usually this is a conflict between Ids, or some kind of knockout bindings

**Comment by GylRon1** [comment]
Sorry, I'm not the smartest when it comes to programming, I don't know where to find the devtools (F12). I'm working with the Chrome browser if that can help?

**Comment by iFrostizz** [comment]
Just enable Calibration Companion, go in the SpoolManager tab (where it's broken), and press "F12". Here, a tab should open, and head on "Console". There might be some errors in red. If so, please provide me a screenshot

**Comment by GylRon1** [comment]
![2021-05-13 23_48_53-Window](https://user-images.githubusercontent.com/84151858/118192258-2831e100-b446-11eb-94e0-fdaefecf9914.png)
Here you go.

**Comment by iFrostizz** [comment]
I don't think that this is the error I'm searching for, I see that they are 33 errors 
![image](https://user-images.githubusercontent.com/51274081/118251917-d83c3400-b4b0-11eb-8b0f-4de76c199208.png)
Do you spot anything else ?

**Comment by GylRon1** [comment]
Hello iFrostizz, the other errors were network related. I prepared another Raspberry Pi (4B 8GB) with latest octopi and newest Octoprint with the same plugins and notice the same problem. I don't have a printer attached, but tested on my regular Octoprint that it does not matter for the error to occure. I have attached the console output on the fresh install. There are no other errors, only 6 warnings. Hope this helps.
![2021-05-14 17_51_37-Window](https://user-images.githubusercontent.com/84151858/118297181-1a2f9f00-b4de-11eb-802e-5974da54bad1.png)

**Comment by iFrostizz** [comment]
Thanks, it was a css from my plugin. I'm gonna publish an update soon

**Comment by GylRon1** [comment]
Thanks for looking in to it. I appreciate all you guys for the work you do and making this all possible for us (the lesser gifted in programming)!

**Comment by GylRon1** [comment]
Nice, Spoolmanager seems to work properly again after your correction.

Keep up the good work,

Best regards,
Ronny.

Op ma 17 mei 2021 om 10:05 schreef Guyot François ***@***.***
