### ISSUE TITLE
No Temp Setting

### ISSUE THREAD

**Issue by Dogfroster** [iFrostizz/OctoPrint-CalibrationCompanion#8]
No Temp Settings in Gcode.

> 
G28;

;---------ABL METHOD---------
no-abl;
;---------ABL METHOD---------

;---------START G-CODE---------
;
;---------START G-CODE---------

G0 F6000 X121 Y109;
G0 F6000 Z0.2;
;LAYER:0
G1 F1200 X120.459 Y109.047 E0.00000;``

**Comment by iFrostizz** [comment]
Hello, 
Please read this: https://github.com/iFrostizz/OctoPrint-CalibrationCompanion#profiles
