### ISSUE TITLE
Bed leveling tab does nothing

### ISSUE THREAD

**Issue by A-Swafford** [iFrostizz/OctoPrint-CalibrationCompanion#9]
Using an ender3 pro and latest octoprint. The profiles save and load correctly but clicking buttons on tabs other than "save" or "load" does nothing.

Attempted to use bed leveling, PID tune, and print squares. All did nothing.

**Comment by iFrostizz** [comment]
Do you have any files in the file manager ?

**Comment by A-Swafford** [comment]
It totally did add those files, I missed the part in the instructions where I would need to manually start the files going. I interpreted "file would be added to manager to..." meaning it would be auto started (like what prusa does). Thanks!

**Comment by iFrostizz** [comment]
I could do that but I prefere to let the control to the user :)

**Comment by iFrostizz** [comment]
An "auto-print" feature has been added in the setup tab of the 1.0.1 version
